import {test,expect} from '@playwright/test';
import 'dotenv/config';
import {PrismaClient} from '../../generated/prisma/client';
import {PrismaPg} from '@prisma/adapter-pg';
import bcrypt from 'bcrypt';
const db=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL})});
const stamp=Date.now(),ownerEmail=`owner-${stamp}@example.com`,workerEmail=`worker-${stamp}@example.com`,password='Strong test password 2026';let shopId='',ownerId='',workerId='';
test.beforeAll(async()=>{const owner=await db.user.create({data:{name:'Shop Owner',email:ownerEmail,passwordHash:await bcrypt.hash(password,12)}});ownerId=owner.id;shopId=(await db.shop.create({data:{ownerId,name:'Market Sales'}})).id;});
test.afterAll(async()=>{if(shopId){await db.saleCollection.deleteMany({where:{sale:{shopId}}});await db.sale.deleteMany({where:{shopId}});await db.handover.deleteMany({where:{shopId}});await db.stockEntry.deleteMany({where:{shopId}});await db.item.deleteMany({where:{shopId}});await db.shopMember.deleteMany({where:{shopId}});await db.shop.delete({where:{id:shopId}});}await db.user.deleteMany({where:{id:{in:[ownerId,workerId].filter(Boolean)}}});await db.$disconnect();});
test('owner and worker: items, invitation, sale, payments, handovers and stock protection',async({page,browser})=>{
 await page.goto('/login');await page.getByLabel('Email address').fill(ownerEmail);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(new RegExp(`/dashboard/${shopId}$`));
 await page.goto(`/dashboard/${shopId}?tab=settings`);await page.getByLabel('Currency',{exact:true}).selectOption('USD');await page.getByRole('button',{name:'Save currency'}).click();await expect(page.locator('.shop-label')).toContainText('US dollar · USD');expect((await db.shop.findUniqueOrThrow({where:{id:shopId}})).currency).toBe('USD');const currencyCsv=await page.request.get(`/api/sales/export?shopId=${shopId}`);expect(await currencyCsv.text()).toContain('Unit price (USD)');await page.getByLabel('Currency',{exact:true}).selectOption('GMD');await page.getByRole('button',{name:'Save currency'}).click();await expect(page.locator('.shop-label')).toContainText('Gambian dalasi · GMD');
 await page.goto(`/dashboard/${shopId}?tab=items`);await page.getByLabel('Item name',{exact:true}).fill('Rice bag');await page.getByLabel('Selling price (GMD)').fill('150');await page.getByLabel('Starting stock').fill('5');await page.getByLabel('Employee percentage (%)').fill('12.5');
 const addRequest=page.waitForRequest(r=>r.method()==='POST'&&r.url().includes(`/dashboard/${shopId}`));await page.getByRole('button',{name:'Add item',exact:true}).click();const captured=await addRequest;await expect(page.getByRole('heading',{name:'Rice bag'})).toBeVisible();
 const item=await db.item.findFirstOrThrow({where:{shopId}});
 await page.goto(`/dashboard/${shopId}?tab=team`);await page.getByLabel('Worker email').fill(workerEmail);await page.getByRole('button',{name:'Create invitation'}).click();const invitation=page.getByRole('link',{name:'Open invitation'});await expect(invitation).toBeVisible();const join=await invitation.getAttribute('href');
 const context=await browser.newContext();const worker=await context.newPage();await worker.goto(join!);await worker.getByRole('link',{name:'Create your worker account'}).click();await worker.getByLabel('Your name').fill('Sales Worker');await worker.getByLabel('Email address').fill(workerEmail);await worker.getByLabel('Password',{exact:true}).fill(password);await worker.getByLabel('Confirm password').fill(password);await worker.getByRole('button',{name:'Create account'}).click();await expect(worker.getByRole('button',{name:'Join sales book'})).toBeVisible();await worker.getByRole('button',{name:'Join sales book'}).click();await expect(worker.getByRole('heading',{name:'Your business at a glance.'})).toBeVisible();workerId=(await db.user.findUniqueOrThrow({where:{email:workerEmail}})).id;
 // Replay an owner mutation with worker cookies: UI hiding alone must not authorize it.
 const headers=await captured.allHeaders();const replay=await context.request.post(captured.url(),{headers:{'content-type':headers['content-type'],'next-action':headers['next-action'],origin:new URL(captured.url()).origin},data:captured.postDataBuffer()!});expect(await replay.text()).toContain('Only the owner');expect(await db.item.count({where:{shopId}})).toBe(1);
 await worker.goto(`/dashboard/${shopId}?tab=new`);await worker.getByLabel('Quantity',{exact:true}).fill('2');await worker.getByLabel('Payment',{exact:true}).selectOption('partial');await worker.getByLabel('Amount received (GMD)').fill('200');await worker.getByLabel('Customer name',{exact:false}).fill('Awa');await expect(worker.locator('.sale-total strong')).toHaveText('D 300.00');await worker.getByRole('button',{name:'Record sale',exact:true}).click();await expect(worker.getByText('Sale recorded.',{exact:true})).toBeVisible();
 const sale=await db.sale.findFirstOrThrow({where:{shopId}});expect(sale.totalMinor).toBe(30000);expect(sale.paidMinor).toBe(20000);expect(sale.employeePercentageBps).toBe(1250);expect(sale.commissionMinor).toBe(3750);
 await db.item.update({where:{id:item.id},data:{employeePercentageBps:2000}});expect((await db.sale.findUniqueOrThrow({where:{id:sale.id}})).commissionMinor).toBe(3750);expect((await db.item.findUniqueOrThrow({where:{id:item.id}})).stock).toBe(3);
 await worker.goto(`/dashboard/${shopId}?tab=sales`);await worker.locator('.sale-details summary').first().click();await worker.getByLabel('Additional amount received (GMD)').fill('100');await worker.getByRole('button',{name:'Record payment'}).click();await expect(worker.getByText('Paid in full.',{exact:true})).toBeVisible();expect((await db.sale.findUniqueOrThrow({where:{id:sale.id}})).paidMinor).toBe(30000);
 await page.goto(`/dashboard/${shopId}?tab=money`);await page.getByLabel('Amount received (GMD)').fill('250');await page.getByRole('button',{name:'Confirm money received'}).click();await expect(page.getByText('Money received recorded.',{exact:true})).toBeVisible();await worker.goto(`/dashboard/${shopId}?tab=money`);await expect(worker.locator('.primary-metric h2')).toHaveText('D 50.00');await expect(worker.getByRole('button',{name:'Confirm money received'})).toHaveCount(0);
 await page.goto(`/dashboard/${shopId}?tab=items`);await page.getByText('Add or correct stock',{exact:true}).click();await page.getByLabel('Quantity change').fill('-2');await page.getByLabel('Reason',{exact:true}).fill('Damaged bags');await page.getByRole('button',{name:'Update stock'}).click();await expect(page.getByText('Saved.',{exact:true})).toBeVisible();
 const second=await context.newPage();for(const p of [worker,second])await p.goto(`/dashboard/${shopId}?tab=new`);
 await Promise.all([worker.getByRole('button',{name:'Record sale',exact:true}).click(),second.getByRole('button',{name:'Record sale',exact:true}).click()]);await expect.poll(()=>db.sale.count({where:{shopId}})).toBe(2);await expect.poll(async()=>(await db.item.findUniqueOrThrow({where:{id:item.id}})).stock).toBe(0);
 const csv=await context.request.get(`/api/sales/export?shopId=${shopId}`);expect(csv.status()).toBe(200);expect(await csv.text()).toContain('Rice bag');
 await page.goto(`/dashboard/${shopId}`);await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/private/tmp/salesbook-dashboard-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'/private/tmp/salesbook-dashboard-mobile.png',fullPage:true});
 await worker.setViewportSize({width:390,height:844});await worker.goto(`/dashboard/${shopId}?tab=money`);expect(await worker.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await worker.screenshot({path:'/private/tmp/salesbook-worker-mobile.png',fullPage:true});
 // Selling the last unit must select the next available item without a reload.
 await db.item.createMany({data:[{shopId,name:'Apples',priceMinor:1000,stock:1},{shopId,name:'Bananas',priceMinor:2000,stock:1}]});
 await worker.goto(`/dashboard/${shopId}?tab=new`);await expect(worker.locator('.sale-total strong')).toHaveText('D 10.00');await worker.getByRole('button',{name:'Record sale',exact:true}).click();await expect(worker.locator('.sale-total strong')).toHaveText('D 20.00');await expect(worker.getByRole('button',{name:'Record sale',exact:true})).toBeEnabled();await worker.getByRole('button',{name:'Record sale',exact:true}).click();await expect(worker.getByRole('heading',{name:'No items available'})).toBeVisible();await expect(worker.getByRole('status')).toHaveText('Sale recorded.');
 await page.goto(`/dashboard/${shopId}?tab=sales&page=1.5`);await expect(page.getByRole('heading',{name:'Every sale, in one place.'})).toBeVisible();
 // Correct a handover before refunding its sale; keep the audit trail and restore stock.
 await page.goto(`/dashboard/${shopId}?tab=money`);await page.getByText('Correct this handover',{exact:true}).click();await page.getByLabel('Reason',{exact:true}).fill('Handover recorded in error');await page.getByRole('button',{name:'Void handover',exact:true}).click();await expect(page.getByText('Handover recorded in error',{exact:true})).toBeVisible();
 await page.goto(`/dashboard/${shopId}?tab=sales`);const original=page.locator('.sale-details > details').filter({has:page.locator('summary').filter({hasText:'Rice bag · D 300.00'})});await original.locator('summary').first().click();await original.getByText('Void this sale',{exact:true}).click();await original.getByLabel('Reason',{exact:true}).fill('Full return and refund');await original.getByRole('button',{name:'Confirm void',exact:true}).click();await expect(original.getByText('Voided: Full return and refund',{exact:true})).toBeVisible();expect((await db.item.findUniqueOrThrow({where:{id:item.id}})).stock).toBe(2);
 // Removing access must immediately block the existing worker session.
 await page.goto(`/dashboard/${shopId}?tab=team`);await page.getByText('Remove access',{exact:true}).click();await page.getByRole('button',{name:'Remove worker access'}).click();await expect(page.getByText('Access removed',{exact:true})).toBeVisible();await worker.goto(`/dashboard/${shopId}`);await expect(worker.getByRole('heading',{name:'Your business at a glance.'})).toHaveCount(0);expect((await context.request.get(`/api/sales/export?shopId=${shopId}`)).status()).toBe(404);
 await context.close();
});
