import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {LayoutDashboard,Receipt,Package,Wallet,Users,Plus,LogOut,ArrowUpRight,Settings} from 'lucide-react';
import {db} from '@/lib/db';
import {requireShop} from '@/services/shops';
import {Brand} from '@/components/brand';
import {ActionForm} from '@/components/action-form';
import {DashboardStatistics} from '@/components/dashboard-statistics';
import {SaleForm} from '@/components/sale-form';
import {saveSaleData} from '@/actions/sales';
import {logout} from '@/actions/auth';
import {money as formatCurrency,amountInput,dateRange} from '@/lib/money';
import {currencyCodes,currencyNames,type CurrencyCode} from '@/lib/currency';
function Fields({id,op}:{id:string;op:string}){return <><input type="hidden" name="shopId" value={id}/><input type="hidden" name="op" value={op}/><input type="hidden" name="requestKey" value={randomUUID()}/></>;}
const formatDate=(date:Date)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Banjul',dateStyle:'medium',timeStyle:'short'}).format(date);
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{tab?:string;from?:string;to?:string;seller?:string;page?:string}>}){
 const {id}=await params;const {shop,user,isOwner}=await requireShop(id);const q=await searchParams;const tab=q.tab??'overview';const page=Math.max(1,Math.min(100000,Math.floor(Number(q.page))||1));
 const money=(value:number)=>formatCurrency(value,shop.currency);const currencyName=currencyNames[shop.currency as CurrencyCode]??shop.currency;
 const scope={shopId:id,...(!isOwner?{sellerId:user.id}:{})};const filter={...scope,soldAt:dateRange(q.from,q.to),...(isOwner&&q.seller?{sellerId:q.seller}:{})};
 const [items,members,sales,sums,allSums,handovers,saleCount,stockEntries,productStats,employeeStats]=await Promise.all([
  db.item.findMany({where:{shopId:id},orderBy:{name:'asc'}}),db.shopMember.findMany({where:{shopId:id},include:{user:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:'asc'}}),
  db.sale.findMany({where:filter,include:{seller:{select:{name:true}},collections:{orderBy:{createdAt:'asc'}}},orderBy:{soldAt:'desc'},skip:(page-1)*50,take:50}),
  db.sale.aggregate({where:{...filter,voidedAt:null},_sum:{totalMinor:true,paidMinor:true,quantity:true,commissionMinor:true},_count:true}),
  db.sale.groupBy({by:['sellerId'],where:{shopId:id,voidedAt:null},_sum:{paidMinor:true,totalMinor:true}}),
  db.handover.findMany({where:{shopId:id,...(!isOwner?{workerId:user.id}:{})},include:{worker:{select:{name:true}}},orderBy:{createdAt:'desc'}}),
  db.sale.count({where:filter}),db.stockEntry.findMany({where:{shopId:id},include:{item:{select:{name:true}}},orderBy:{createdAt:'desc'},take:20}),
  db.sale.groupBy({by:['itemId'],where:{...filter,voidedAt:null},_sum:{quantity:true,totalMinor:true}}),
  db.sale.groupBy({by:['sellerId'],where:{...filter,voidedAt:null},_sum:{quantity:true,totalMinor:true}})
 ]);
 const workerBalance=(workerId:string)=>(allSums.find(s=>s.sellerId===workerId)?._sum.paidMinor??0)-handovers.filter(h=>h.workerId===workerId&&!h.voidedAt).reduce((n,h)=>n+h.amountMinor,0);
 const held=isOwner?members.reduce((n,m)=>n+workerBalance(m.userId),0):workerBalance(user.id);
 const handed=handovers.filter(h=>!h.voidedAt).reduce((n,h)=>n+h.amountMinor,0);
 const total=sums._sum.totalMinor??0,received=sums._sum.paidMinor??0;
 const nav=[{key:'overview',name:'Overview',icon:LayoutDashboard},{key:'new',name:'Record sale',icon:Plus},{key:'sales',name:'Sales history',icon:Receipt},{key:'items',name:'Items & stock',icon:Package},{key:'money',name:'Money handovers',icon:Wallet},...(isOwner?[{key:'team',name:'Your worker',icon:Users},{key:'settings',name:'Settings',icon:Settings}]:[])];
 const titles:Record<string,string>={overview:'Your business at a glance.',new:'Record a sale.',sales:'Every sale, in one place.',items:'Your items & stock.',money:'Keep the money clear.',team:'Work better, together.',settings:'Business settings.'};
 const exportParams=new URLSearchParams({shopId:id,...(q.from?{from:q.from}:{}),...(q.to?{to:q.to}:{}),...(q.seller?{seller:q.seller}:{})});
 return <div className="workspace sales-workspace"><aside className="sidebar"><Brand href={`/dashboard/${id}`}/><div className="shop-label"><strong>{shop.name}</strong><span>{currencyName} · {shop.currency}</span></div><nav aria-label="Main navigation"><Link href="/dashboard?view=all"><LayoutDashboard size={18}/>Sales books</Link>{nav.map(n=><Link key={n.key} aria-current={tab===n.key?'page':undefined} className={tab===n.key?'nav-active':''} href={`/dashboard/${id}?tab=${n.key}`}><n.icon size={18}/>{n.name}</Link>)}</nav><div className="sidebar-bottom"><span>{user.name}</span><small>{isOwner?'Owner':'Worker'} · {user.email}</small><form action={logout}><button className="logout"><LogOut size={16}/>Sign out</button></form></div></aside>
 <main id="main" className="dashboard sales-dashboard"><div className="dashboard-top"><span className="eyebrow">{shop.name.toUpperCase()}</span><span className="pill">{isOwner?'Owner workspace':'Worker workspace'}</span></div><div className="section-heading page-heading"><div><h1>{titles[tab]??titles.overview}</h1><p className="muted">{isOwner?'Follow your sales, stock and the money coming back to you.':'Record what you sell and see your own sales and handovers.'}</p></div>{tab!=='new'&&<Link className="button" href={`?tab=new`}><Plus size={18}/>Record sale</Link>}</div>
 {(tab==='overview'||tab==='sales')&&<><form className="filter-bar" method="get"><input type="hidden" name="tab" value={tab}/><label>From<input type="date" name="from" defaultValue={q.from}/></label><label>To<input type="date" name="to" defaultValue={q.to}/></label>{isOwner&&<label>Sold by<select name="seller" aria-label="Sold by" defaultValue={q.seller??''}><option value="">Everyone</option><option value={user.id}>You</option>{members.map(m=><option key={m.id} value={m.userId}>{m.user.name}</option>)}</select></label>}<button className="button secondary">Apply</button><Link className="text-link" href={`?tab=${tab}`}>Reset</Link></form>
 <div className="sales-stats"><article className="panel metric primary-metric"><span>Total sales</span><h2>{money(total)}</h2><small>{sums._count} sales · {sums._sum.quantity??0} items sold</small></article><article className="panel metric"><span>Money collected</span><h2>{money(received)}</h2><small>Received against these sales</small></article><article className="panel metric"><span>Customer balances</span><h2>{money(total-received)}</h2><small>Still unpaid against these sales</small></article><article className="panel metric"><span>{isOwner?'Held by worker(s)':'Money you hold'}</span><h2>{money(held)}</h2><small>All time, after confirmed handovers</small></article></div>
 {tab==='overview'&&<DashboardStatistics
  products={items.map(item=>({id:item.id,name:item.name,stock:item.stock,active:item.active,units:productStats.find(s=>s.itemId===item.id)?._sum.quantity??0}))}
  employees={[{id:shop.ownerId,name:isOwner?`${user.name} (owner)`:'Owner'},...members.filter(m=>m.userId!==shop.ownerId).map(m=>({id:m.userId,name:m.user.name}))].filter(m=>isOwner||m.id===user.id).filter(m=>!q.seller||!isOwner||m.id===q.seller).map(m=>({...m,units:employeeStats.find(s=>s.sellerId===m.id)?._sum.quantity??0,revenue:employeeStats.find(s=>s.sellerId===m.id)?._sum.totalMinor??0}))}
  total={total} units={sums._sum.quantity??0} currency={shop.currency} isOwner={isOwner}
 />}
 <section className="panel"><h2>Employee commission</h2><strong>{money(sums._sum.commissionMinor??0)}</strong><p className="small muted">Based on full sale totals in this period, including unpaid sales. Voided sales are excluded. Commission is tracked separately from money handovers.</p></section>
 <section className="panel ledger-panel"><div className="section-heading"><div><span className="eyebrow">YOUR SALES BOOK</span><h2>{tab==='overview'?'Recent sales':'Sales history'}</h2></div><a className="text-link" href={`/api/sales/export?${exportParams}`}>Download CSV <ArrowUpRight size={16}/></a></div>
 {sales.length?<><div className="table-scroll"><table><thead><tr><th>Item / date</th><th>Sold by</th><th>Qty</th><th>Unit price</th><th>Total</th><th>Received</th><th>Unpaid</th><th>Commission</th><th>Status</th></tr></thead><tbody>{sales.map(s=><tr key={s.id} className={s.voidedAt?'void-row':''}><td><strong>{s.itemName}</strong><small>{formatDate(s.soldAt)}</small>{s.customerName&&<small>{s.customerName}</small>}</td><td>{s.seller.name}</td><td>{s.quantity}</td><td>{money(s.unitPriceMinor)}</td><td>{money(s.totalMinor)}</td><td>{money(s.paidMinor)}</td><td>{money(s.totalMinor-s.paidMinor)}</td><td>{money(s.voidedAt?0:s.commissionMinor)}<small>{s.employeePercentageBps/100}%</small></td><td><span className={`pill ${s.voidedAt?'status-void':s.paidMinor===s.totalMinor?'status-paid':'status-due'}`}>{s.voidedAt?'Voided':s.paidMinor===s.totalMinor?'Paid':s.paidMinor?'Partly paid':'Unpaid'}</span></td></tr>)}</tbody></table></div><p className="small muted">Showing {(page-1)*50+1}–{Math.min(page*50,saleCount)} of {saleCount} sales. Dates use Gambia time. Voided sales are excluded from totals.</p><div className="pagination">{page>1&&<Link href={`?${new URLSearchParams({...q,tab,page:String(page-1)})}`}>← Previous</Link>}{saleCount>page*50&&<Link href={`?${new URLSearchParams({...q,tab,page:String(page+1)})}`}>Next →</Link>}</div></>:<div className="empty"><Receipt size={32}/><h3>No sales in this period</h3><p>{items.length?'Record your first sale to start your sales book.':'Add your items and starting stock to get started.'}</p><Link className="text-link" href={`?tab=${items.length?'new':'items'}`}>{items.length?'Record sale':'View items'} →</Link></div>}</section>
 {tab==='overview'&&<div className="management-grid overview-bottom"><section className="panel"><h2>Stock to watch</h2>{items.filter(i=>i.active&&i.stock<=5).length?items.filter(i=>i.active&&i.stock<=5).map(i=><div className="summary-row" key={i.id}><span>{i.name}</span><strong className={i.stock===0?'negative':''}>{i.stock} left</strong></div>):<p className="muted">No items are running low.</p>}<Link className="text-link" href="?tab=items">View all items →</Link></section><section className="panel"><h2>Money handed over</h2><div className="big-number">{money(handed)}</div><p className="muted">All confirmed handovers, across all dates.</p><Link className="text-link" href="?tab=money">View handovers →</Link></section></div>}
 {tab==='sales'&&sales.length>0&&<section className="sale-details"><h2>Sale details & corrections</h2>{sales.map(s=><details className="panel" key={s.id}><summary>{s.itemName} · {money(s.totalMinor)} · {formatDate(s.soldAt)}</summary><p>Seller: {s.seller.name} · Customer: {s.customerName||'Not recorded'}</p>{s.note&&<p>Note: {s.note}</p>}{s.collections.map(c=><p className="small muted" key={c.id}>Collected {money(c.amountMinor)} · {formatDate(c.createdAt)}</p>)}{s.voidedAt?<p className="muted">Voided: {s.voidReason}</p>:<>{s.paidMinor===s.totalMinor&&<p className="success" role="status">Paid in full.</p>}{s.paidMinor<s.totalMinor&&<ActionForm action={saveSaleData} label="Record payment"><Fields id={id} op="collect"/><input type="hidden" name="saleId" value={s.id}/><p className="small">Record money collected by {s.seller.name}. Remaining: {money(s.totalMinor-s.paidMinor)}.</p><label>Additional amount received ({shop.currency})
 </label></ActionForm>}{isOwner&&<details><summary>Void this sale</summary><ActionForm action={saveSaleData} label="Confirm void"><Fields id={id} op="voidSale"/><input type="hidden" name="saleId" value={s.id}/><p className="small">Use for an incorrect sale or a full return with the money refunded. This restores {s.quantity} units to stock and removes this sale from totals. The record stays visible.</p><label>Reason<input name="reason" required minLength={3} maxLength={300}/></label></ActionForm></details>}</>}</details>)}</section>}</>}
 {tab==='new'&&<div className="sale-entry-grid"><section className="panel"><SaleForm shopId={id} items={items.filter(i=>i.active&&i.stock>0).map(i=>({id:i.id,name:i.name,priceMinor:i.priceMinor,stock:i.stock}))} requestKey={randomUUID()} currency={shop.currency}/></section><aside className="entry-help"><span className="eyebrow">KEEP A CLEAR RECORD</span><h2>A few details.<br/>Everything adds up.</h2><p>Choose the item and quantity. The price and total are calculated for you.</p><p>For a partly paid sale, enter the money received and the customer’s name. You can record the remaining payment later.</p><div className="pill">{currencyName} ({shop.currency})</div></aside></div>}
 {tab==='items'&&<><div className="management-grid"><section>{isOwner&&<details className="panel" open={!items.length}><summary>Add an item</summary><ActionForm action={saveSaleData} label="Add item"><Fields id={id} op="item"/><label>Item name<input name="name" required minLength={2} maxLength={100}/></label><div className="form-grid"><label>Selling price ({shop.currency})
 <input name="price" type="number" min="0" max="9999999.99" step="0.01" required/></label><label>Starting stock<input name="stock" type="number" min="0" max="1000000" defaultValue={0} required/></label><label>Employee percentage (%)<input name="employeePercentage" type="number" min="0" max="100" step="0.01" defaultValue={10}/></label></div></ActionForm></details>}{!items.length&&<div className="empty">No items yet.</div>}{items.map(item=><article className="panel item-card" key={item.id}><div className="section-heading"><div><h3>{item.name}</h3><span className="muted">{money(item.priceMinor)} each</span><small className="muted">Employee percentage: {item.employeePercentageBps/100}%</small></div><div><strong className="stock-number">{item.stock}</strong><small className="muted">in stock</small></div></div><span className="pill">{item.active?'Available':'Archived'}</span>{isOwner&&<><details><summary>Edit item & price</summary><ActionForm action={saveSaleData}><Fields id={id} op="item"/><input type="hidden" name="itemId" value={item.id}/><label>Item name<input name="name" defaultValue={item.name} required minLength={2} maxLength={100}/></label><label>Selling price ({shop.currency})
 <input name="price" type="number" min="0" max="9999999.99" step="0.01" defaultValue={amountInput(item.priceMinor)} required/></label><label>Employee percentage (%)<input name="employeePercentage" type="number" min="0" max="100" step="0.01" defaultValue={item.employeePercentageBps/100}/></label></ActionForm></details><details><summary>Add or correct stock</summary><ActionForm action={saveSaleData} label="Update stock"><Fields id={id} op="restock"/><input type="hidden" name="itemId" value={item.id}/><label>Quantity change<input name="quantity" type="number" min={-item.stock} max={1000000-item.stock} required placeholder="10 to add, -2 to remove"/></label><label>Reason<input name="note" required minLength={2} maxLength={200} placeholder="New delivery, damaged items…"/></label></ActionForm></details><ActionForm action={saveSaleData} label={item.active?'Archive item':'Restore item'}><Fields id={id} op="toggle"/><input type="hidden" name="itemId" value={item.id}/></ActionForm></>}</article>)}</section><section className="panel"><h2>Stock adjustments</h2><p className="small muted">Latest deliveries and corrections. Sales reduce stock automatically.</p>{stockEntries.length?stockEntries.map(s=><div className="summary-row" key={s.id}><div><strong>{s.item.name}</strong><small>{s.note} · {formatDate(s.createdAt)}</small></div><strong>{s.quantity>0?'+':''}{s.quantity}</strong></div>):<p className="muted">No stock adjustments yet.</p>}</section></div></>}
 {tab==='money'&&<><div className="sales-stats two-stats"><article className="panel metric primary-metric"><span>{isOwner?'Still with worker(s)':'Money you hold'}</span><h2>{money(held)}</h2><small>Collected from sales minus confirmed handovers</small></article><article className="panel metric"><span>Handed over</span><h2>{money(handed)}</h2><small>All time · confirmed by the owner</small></article></div>{isOwner&&<div className="management-grid"><section className="panel"><h2>Confirm money received</h2>{members.length?<ActionForm action={saveSaleData} label="Confirm money received"><Fields id={id} op="handover"/><label>Worker<select name="workerId" aria-label="Worker">{members.map(m=><option value={m.userId} key={m.id}>{m.user.name} · holds {money(workerBalance(m.userId))}</option>)}</select></label><label>Amount received ({shop.currency})
 <input name="amount" type="number" min="0.01" max="9999999.99" step="0.01" required/></label><label>Note (optional)<input name="note" maxLength={300} placeholder="Cash received, bank transfer…"/></label><p className="small muted">Record this only after you have received the money.</p></ActionForm>:<p>Invite your worker first.</p>}</section><section className="panel"><h2>Worker balances</h2>{members.map(m=><div className="summary-row" key={m.id}><span>{m.user.name}{!m.active&&' (access removed)'}</span><strong>{money(workerBalance(m.userId))}</strong></div>)}<p className="small muted">Your own sales are already held by you and are not included in worker balances.</p></section></div>}
 <section className="panel ledger-panel"><h2>Handover history</h2>{handovers.length?handovers.map(h=><article className="handover-row" key={h.id}><div className="section-heading"><div><strong>{h.worker.name}</strong><small>{formatDate(h.createdAt)}</small></div><strong>{money(h.amountMinor)}</strong></div><p className="small">{h.note||'Money received'} · {h.voidedAt?'Voided':'Confirmed'}</p>{h.voidReason&&<p className="small muted">{h.voidReason}</p>}{isOwner&&!h.voidedAt&&<details><summary>Correct this handover</summary><ActionForm action={saveSaleData} label="Void handover"><Fields id={id} op="voidHandover"/><input type="hidden" name="handoverId" value={h.id}/><label>Reason<input name="reason" required minLength={3} maxLength={300}/></label><p className="small">Voiding returns this amount to the worker’s outstanding balance.</p></ActionForm></details>}</article>):<div className="empty">No money handovers recorded yet.</div>}</section></>}
 {tab==='team'&&isOwner&&<div className="management-grid"><section className="panel"><h2>Invite your worker</h2><p className="muted">Your worker can record sales and view their own records. Only you can change prices, stock and handovers.</p><ActionForm action={saveSaleData} label="Create invitation"><Fields id={id} op="invite"/><label>Worker email<input name="email" type="email" required maxLength={254}/></label><p className="small muted">Share the private link with your worker. It expires after seven days. A new invitation replaces any unused invitation for that email.</p></ActionForm></section><section><h2>Your team</h2><article className="panel"><h3>{user.name}</h3><p>{user.email}</p><span className="pill">Owner</span></article>{members.map(m=><article className="panel item-card" key={m.id}><h3>{m.user.name}</h3><p>{m.user.email}</p><span className="pill">{m.active?'Worker':'Access removed'}</span>{m.active&&<details><summary>Remove access</summary><ActionForm action={saveSaleData} label="Remove worker access"><Fields id={id} op="removeWorker"/><input type="hidden" name="memberId" value={m.id}/><p className="small">Past sales and money records are kept.</p></ActionForm></details>}</article>)}<details className="panel"><summary>Business name</summary><ActionForm action={saveSaleData}><Fields id={id} op="rename"/><label>Business name<input name="name" defaultValue={shop.name} required minLength={2} maxLength={100}/></label></ActionForm></details></section></div>}
 {tab==='settings'&&isOwner&&<div className="management-grid"><section className="panel"><h2>Currency</h2><ActionForm action={saveSaleData} label="Save currency"><Fields id={id} op="currency"/><label>Currency<select name="currency" defaultValue={shop.currency}>{currencyCodes.map(code=><option key={code} value={code}>{currencyNames[code]} ({code})</option>)}</select></label><p className="small muted">Changing currency updates how amounts are labeled. Existing amounts are not converted using exchange rates.</p></ActionForm></section><section className="panel"><h2>Business name</h2><ActionForm action={saveSaleData}><Fields id={id} op="rename"/><label>Business name<input name="name" defaultValue={shop.name} required minLength={2} maxLength={100}/></label></ActionForm></section></div>}
 </main></div>;
}
